### ISSUE TITLE
Cavalry.png not found

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-maps/new_world_order1915lebowski#1]
From: http://tripleadev.1671093.n2.nabble.com/Cannot-play-NewWorldOrder1915-Lebowski-td7592646.html;cid=1467000788276-76

triplea.engine.version.bin:1.8.0.9 
Player, Germans attacks a Neutral territory, and should have had to pay -9999, but did not have enough PUs to pay! This is a bug. 
Player, Germans attacks a Neutral territory, and should have had to pay -9999, but did not have enough PUs to pay! This is a bug. 

Exception: Cant load: Cavalry  looking in: units/Americans/Cavalry.png 
games.strategy.triplea.image.UnitImageFactory.getBaseImageURL(UnitImageFactory.java:146) 
games.strategy.triplea.image.UnitImageFactory.getBaseImageURL(UnitImageFactory.java:137) 
games.strategy.triplea.image.UnitImageFactory.getBaseImage(UnitImageFactory.java:152) 
games.strategy.triplea.image.UnitImageFactory.getIcon(UnitImageFactory.java:187) 
games.strategy.triplea.ui.ProductionPanel$Rule.getPanelComponent(ProductionPanel.java:285) 
games.strategy.triplea.ui.TabbedProductionPanel.getRulesPanel(TabbedProductionPanel.java:207) 
games.strategy.triplea.ui.TabbedProductionPanel.initLayout(TabbedProductionPanel.java:71) 
games.strategy.triplea.ui.ProductionPanel.show(ProductionPanel.java:78) 
games.strategy.triplea.ui.TabbedProductionPanel.getProduction(TabbedProductionPanel.java:43) 
games.strategy.triplea.ui.PurchasePanel$4.actionPerformed(PurchasePanel.java:124) 
games.strategy.triplea.ui.PurchasePanel$3.run(PurchasePanel.java:109) 
java.awt.event.InvocationEvent.dispatch(Unknown Source) 
java.awt.EventQueue.dispatchEventImpl(Unknown Source) 
java.awt.EventQueue.access$500(Unknown Source) 
java.awt.EventQueue$3.run(Unknown Source) 
java.awt.EventQueue$3.run(Unknown Source) 
java.security.AccessController.doPrivileged(Native Method) 
java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source) 
java.awt.EventQueue.dispatchEvent(Unknown Source) 
java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source) 
java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source) 
java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source) 
java.awt.EventDispatchThread.pumpEvents(Unknown Source) 
java.awt.EventDispatchThread.pumpEvents(Unknown Source) 
java.awt.EventDispatchThread.run(Unknown Source)

**Comment by CharlieAtlas** [comment]
Fixed!
https://github.com/triplea-maps/new_world_order1915lebowski/pull/5
